// Builds dist/: the ESM entry (elements + Lit bundled in, React external),
// its .d.ts, and one flattened stylesheet that carries the whole theme.
//
// dist/styles.css is what a consumer (or the Claude Design sync) loads: the
// theme's fonts, its two token layers, the Expressive system defaults and the
// bridge, in that order — the same order the repo's own pages link them.
import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkg = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(pkg, '..');
const dist = resolve(pkg, 'dist');
rmSync(dist, { recursive: true, force: true });
mkdirSync(resolve(dist, 'fonts'), { recursive: true });

// labs/gb imports its stylesheets as CSS module scripts, which esbuild does
// not bundle; each becomes a constructed CSSStyleSheet (what Lit accepts).
const cssModuleScripts = {
  name: 'css-module-scripts',
  setup(b) {
    b.onResolve({ filter: /\.css$/ }, (a) =>
      a.with?.type === 'css' ? { path: resolve(dirname(a.importer), a.path), namespace: 'css-sheet' } : undefined);
    b.onLoad({ filter: /.*/, namespace: 'css-sheet' }, (a) => ({
      contents: `const s = new CSSStyleSheet(); s.replaceSync(${JSON.stringify(readFileSync(a.path, 'utf8'))}); export default s;`,
      loader: 'js',
    }));
  },
};

await build({
  entryPoints: [resolve(pkg, 'src/index.ts')],
  outfile: resolve(dist, 'index.js'),
  bundle: true,
  format: 'esm',
  target: 'es2021',
  external: ['react', 'react-dom'],
  legalComments: 'none',
  plugins: [cssModuleScripts],
  logLevel: 'warning',
});

// TypeScript's own JS entry, run by this Node: node_modules/.bin/tsc is a shell
// script on macOS and Linux but a .cmd wrapper on Windows, which execFileSync
// cannot start without a shell.
execFileSync(process.execPath, [resolve(pkg, 'node_modules/typescript/bin/tsc'),
  'src/index.ts', '--declaration', '--emitDeclarationOnly', '--outDir', 'dist',
  '--target', 'es2022', '--module', 'esnext', '--moduleResolution', 'bundler',
  '--skipLibCheck', '--jsx', 'react-jsx',
], { cwd: pkg, stdio: 'inherit' });

// --- the stylesheet ---------------------------------------------------------
// Font url()s are rewritten to ./fonts/<file> and the files copied beside it.
function withLocalFonts(css, fromDir) {
  return css.replace(/url\(\s*['"]?([^'")]+\.woff2)['"]?\s*\)/g, (_, u) => {
    const src = resolve(fromDir, u);
    cpSync(src, resolve(dist, 'fonts', basename(src)));
    return `url(./fonts/${basename(src)})`;
  });
}
// The bridge's icon face is the 67-icon subset; components/icons-full.css
// supplies the complete fonts, so the subset face is dropped here rather than
// shipped and then overridden.
const DROP_SUBSET_FACE = /@font-face\s*\{[^}]*material-symbols-fallback[^}]*\}\s*/;
const part = (rel) => {
  const p = resolve(repo, rel);
  let css = readFileSync(p, 'utf8');
  if (rel === 'components/theme-bridge.css') css = css.replace(DROP_SUBSET_FACE, '');
  return `/* ---- ${rel} ---- */\n${withLocalFonts(css, dirname(p))}`;
};
const parts = [
  'fonts/fonts.css',
  'tokens/base/colors.css', 'tokens/base/typography.css', 'tokens/base/spacing.css', 'tokens/base/effects.css',
  'tokens/m3-expressive.css',
  'components/m3-system.css',
  'components/theme-bridge.css',
  'components/icons-full.css',
];
writeFileSync(resolve(dist, 'styles.css'),
  `/* Material 3 Expressive theme + @material/web Expressive system + bridge.\n   Generated by react/tools/build.mjs from the repo's own files. */\n` +
  parts.map(part).join('\n\n') + '\n');
console.log('dist/index.js, dist/index.d.ts, dist/styles.css');
